### ISSUE TITLE
Tooltips for users on site

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#152]
We want to implement a good tooltip system for site usability.  An example is at https://www.plantphenology.org/ with the little "i" icons that you click on and a little window/frame comes up with user instructions.     Please implement a tooltip (and can use the ? icon that we have currently in the query interface next to the Simple Search Box.).  However, instead of redirecting to a new web page we want to display a tooltip.  For the first tooltip, insert the following text as a response:  "Type any word or phrase here to query all collecting event, sample, and tissue fields"

We need a system for easily adding/modifying tooltip text --- whatever you come up with be sure to document the javascript or HTML with instructions for adding additional tooltips.  The vision here is that we would have lots of tooltips throughout the entire site for giving user help.

**Comment by rodney757** [comment]
Tooltips appear when you hover over something [see here](https://material.angularjs.org/latest/demo/tooltip). I think you more want a dialog/modal then tooltip correct?

We have a popover already in the fastq upload pages, which is between a tooltip & dialog/modal. They are good for short/medium help text.

Otherwise maria, you can use the `$mdDialog` to create a help dialog.

**Comment by jdeck88** [comment]
OK-- lets re-use what we have working on the FASTQ upload pages.  That is perfect!

**Comment by mariadeck** [comment]
@jdeck88 I think you meant to re-assign this todo to yourself, we have the popover now on the query page, we just need to know where else you'd like to use it on the site

**Comment by jdeck88** [comment]
This is done.
