### ISSUE TITLE
Upload photos expedition check?

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#231]
It would be convenient for users to know whether they have permissions to upload to an expedition when uploading photos... current behaviour is that if you do not own the expedition but are a project member you cannot upload photos and you are not informed until the end of photo loading.  A work-around: can we make photos behaves like tissues so any project users can add photos even if they do not own the expedition.  This seems reasonable to me.

**Comment by ewingrj** [comment]
I'm fairly certain tissues don't work this way. The project admin can access any data, but other then that, a user can only access their data.

Currently the photo uploader will ask for an expedition only if the the identifiers are not `uniqueAcrossProject`. If we ask for an expedition, we can do a check however you are limited to uploading a single expedition at a time.

Without asking for an expedition, we would have to parse every file in the zip, extract the parentIdentifier, and run a query to get the expeditions for those parentIdentifiers. I'm concerned parsing a 2gb zip file will crash the browser.

In the meantime, I've made it display a warning stating that you must own the expedition you are upload for, otherwise the upload will fail.

**Comment by jdeck88** [comment]
that sounds like a good plan... i think this is good for now, regarding this ...
closing...
